### ISSUE TITLE
Copy (with attribution!) the DEA Sandbox notebook on STAC use

### ISSUE THREAD

**Issue by alexgleith** [digitalearthafrica/deafrica-sandbox-notebooks#259]
We should bring over the fantastic DEA Sandbox STAC Usage notebook that Robbi created

**Aim:**
Enhance understanding of the DE Africa STAC API

**Study area:**
Notebook example exists: https://docs.dea.ga.gov.au/notebooks/Frequently_used_code/Downloading_data_with_STAC.html

**Scope:**

1. Copy the notebook
2. Adapt it to our environment
3. Enable people to understand how to use the STAC API!

**Input data:**

- n/a

**Expected outcomes and outputs:**

- Enhanced understanding of the capabilities of the STAC API

**Additional information:**

**Comment by cbur24** [comment]
This notebook is now in `Frequently_used_code` folder

**Comment by gumpgourou** [comment]
Thank you. The S3 to HTML and Qgis stream will help a lot of users.

**Comment by gumpgourou** [comment]
Sorry to be picky, but do you think we can add at the top a short text that explains the difference for the user, and is potentially limited hardware/connection, between downloading and streaming?

The [paragraph](https://docs.digitalearthafrica.org/fr/latest/sandbox/notebooks/Frequently_used_code/Downloading_data_with_STAC.html#Streaming-data-without-downloading) could land in the "context" paragraph:

"Due to the increasing size of satellite datasets, downloading data directly to your own local disk can be time-consuming and slow. Sometimes, it is better to stream data directly from the cloud without downloading it first. This can be particularly powerful for data that is stored in the Cloud Optimised GeoTIFF (COG) format which is optimised for efficiently streaming small chunks of an image at a time."

The reason I am asking is that for the announcement in the Helpdesk I would like to take as a process to copy and paste the first two paragraphs of the notebook.

Cheers,

Cedric
