### ISSUE TITLE
Crop Mask No data value

### ISSUE THREAD

**Issue by nanaboamah89** [digitalearthafrica/deafrica-sandbox-notebooks#378]
With the previous regional crop mask, no data =0, while the continental crop mask no data = 255, can the no data value can be 0 instead of 255 for the continental crop mask. 

regional crop mask 
![Screenshot 2022-05-23 at 13 55 23](https://user-images.githubusercontent.com/9433467/169838834-17859824-fa1b-4162-a5a4-ffa203c83b6c.png)

continental crop mask
![Screenshot 2022-05-23 at 14 12 03](https://user-images.githubusercontent.com/9433467/169838969-cb0209cc-3676-4d0e-9779-ba3c3ae4e2ce.png)

**Comment by nanaboamah89** [comment]
![Screenshot 2022-05-23 at 14 39 25](https://user-images.githubusercontent.com/9433467/169844842-5ed30e5c-df83-45a4-8aa3-b7cd0571da38.png)

![Screenshot 2022-05-23 at 14 40 19](https://user-images.githubusercontent.com/9433467/169844866-52f7bef9-42f7-43ca-98b8-4a6465c53bcf.png)

unless we add another line to filter only the crop land before we can get the same regional one.
![Screenshot 2022-05-23 at 14 41 27](https://user-images.githubusercontent.com/9433467/169845442-a7fcd796-9b37-49af-9ae1-9d1b949b1e49.png)

**Comment by alexgleith** [comment]
Hey Edward, this is actually an excellent example of why changing the nodata value is important.

If you look at the data values in the old `_eastern` crop mask here, where purple is `0` and yellow is `1`, you can't distinguish the difference between non-crop and nodata. This is a problem.

<img width="528" alt="image" src="https://user-images.githubusercontent.com/3445853/169927060-d94133a3-a1df-48c7-ab5c-35e58ee84180.png">

The upgraded version looks like this, and note that the nodata values are correctly masked by default in QGIS.

<img width="522" alt="image" src="https://user-images.githubusercontent.com/3445853/169927158-e3c4320b-6d1f-441d-9b11-2ec1a7eb5959.png">

If I unmask them, and set them as red, so values of `255` can be seen, you can see there are now three distinct classes in the data.

<img width="933" alt="image" src="https://user-images.githubusercontent.com/3445853/169927224-6a76116c-de76-4245-a32e-e29ffd522332.png">

This is exactly why we reprocessed the whole continental crop mask: so that we can distinguish between the zero values (in the filtered data it means "not crop") and the nodata values (means there's no decision about it being crop/non-crop).

**Comment by nanaboamah89** [comment]
Hi @alexgleith, thank you for the clarification, I now understand it. I will update the notebooks with the continental crop mask and provide this explanation to it. Will close the issue.
